# NixOS System Configuration
# ─────────────────────────────────────────────────────────────────────────────
# SETUP INSTRUCTIONS:
#   1. Install NixOS normally (let the installer generate hardware config)
#   2. Clone your dotfiles: git clone <repo> ~/configs
#   3. Run: ~/configs/install-script/linux-install.sh
#
# PLACEHOLDERS TO UPDATE:
#   - hostname        → currently "lovelace", change if needed
#   - timezone        → your timezone (timedatectl list-timezones)
# ─────────────────────────────────────────────────────────────────────────────

{ config, pkgs, ... }:

{
  imports = [
    # Hardware config is generated by the NixOS installer — do not commit this
    # It lives at /etc/nixos/hardware-configuration.nix on the machine
    ./hardware-configuration.nix
  ];

  # ── Boot ────────────────────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ── Networking ──────────────────────────────────────────────────────────────
  networking.hostName = "lovelace";
  networking.networkmanager.enable = true;

  # ── Locale & Time ───────────────────────────────────────────────────────────
  time.timeZone = "America/Chicago";
  i18n.defaultLocale = "en_US.UTF-8";

  # ── Desktop (GNOME) ─────────────────────────────────────────────────────────
  services.xserver.enable = true;
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;

  # ── Fonts ───────────────────────────────────────────────────────────────────
  fonts.packages = with pkgs; [
    nerd-fonts.fira-code
    corefonts  # includes Courier New as fallback font
  ];

  # ── Shell ───────────────────────────────────────────────────────────────────
  programs.zsh.enable = true;

  # ── Users ───────────────────────────────────────────────────────────────────
  users.users.aslan = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [ "wheel" "networkmanager" ];
  };

  # ── Allow unfree packages (VSCode, etc.) ────────────────────────────────────
  nixpkgs.config.allowUnfree = true;

  # ── System Packages ─────────────────────────────────────────────────────────
  environment.systemPackages = with pkgs; [

    ##- Core tools
    git
    curl
    wget
    unzip
    gnumake
    gcc

    ##- Shell & navigation
    zsh
    eza        # modern ls replacement
    jump       # smart directory navigation (provides `j`)
    mc         # midnight commander
    ranger     # terminal file manager

    ##- Node / JS tooling
    fnm        # fast node manager

    ##- Terminals
    wezterm
    tabby      # Note: if tabby causes issues, install via flatpak instead
               # (flatpak install flathub dev.eugeny.Tabby)

    ##- Editor & writing
    micro
    vscode
    typora

    ##- Browser
    google-chrome

    ##- Media
    vlc

    ##- GNOME extensions
    gnome-extension-manager       # Matt Jakeman's Extension Manager
    gnomeExtensions.dash-to-panel
    gnomeExtensions.vitals
    # Note: extensions are INSTALLED but must be ENABLED via Extension Manager
    # after first login (GNOME requires a live session to activate extensions)

    ##- Utilities
    nmap
    htop
    tree
    trash-cli

    ##- Gaming
    # Proton is bundled with Steam — no separate package needed
    # Uncomment nvidia line below and set videoDrivers if using an Nvidia GPU

  ];

  # ── Steam ───────────────────────────────────────────────────────────────────
  programs.steam.enable = true;
  hardware.opengl.driSupport32Bit = true;  # required for 32-bit Steam games

  # ── Nvidia (uncomment if using Nvidia GPU) ───────────────────────────────────
  # hardware.nvidia.modesetting.enable = true;
  # services.xserver.videoDrivers = [ "nvidia" ];

  # ── Flatpak (optional fallback for apps not in nixpkgs) ─────────────────────
  services.flatpak.enable = true;
  xdg.portal.enable = true;

  # ── This value determines NixOS compatibility — do not change ───────────────
  system.stateVersion = "24.11";
}
