# NixOS System Configuration
# ─────────────────────────────────────────────────────────────────────────────
# SETUP INSTRUCTIONS:
#   1. Install NixOS normally (let the installer generate hardware config)
#   2. Clone your dotfiles: git clone <repo> ~/configs
#   3. Run: ~/configs/install-script/nixos-install.sh
#
# PLACEHOLDERS TO UPDATE:
#   - "yourhostname"  → your desired machine hostname
#   - "yourusername"  → your actual username
#   - timezone        → your timezone (timedatectl list-timezones)
# ─────────────────────────────────────────────────────────────────────────────

{ config, pkgs, ... }:

{
  imports = [
    # Hardware config is generated by the NixOS installer — do not commit this
    # It lives at /etc/nixos/hardware-configuration.nix on the machine
    ./hardware-configuration.nix
  ];

  # ── Boot ────────────────────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ── Networking ──────────────────────────────────────────────────────────────
  networking.hostName = "yourhostname";
  networking.networkmanager.enable = true;

  # ── Locale & Time ───────────────────────────────────────────────────────────
  time.timeZone = "America/New_York";
  i18n.defaultLocale = "en_US.UTF-8";

  # ── Desktop (GNOME) ─────────────────────────────────────────────────────────
  services.xserver.enable = true;
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;

  # ── Fonts ───────────────────────────────────────────────────────────────────
  fonts.packages = with pkgs; [
    nerd-fonts.fira-code
    corefonts  # includes Courier New as fallback font
  ];

  # ── Shell ───────────────────────────────────────────────────────────────────
  programs.zsh.enable = true;

  # ── Users ───────────────────────────────────────────────────────────────────
  users.users.yourusername = {
    isNormalUser = true;
    shell = pkgs.zsh;
    extraGroups = [ "wheel" "networkmanager" ];
  };

  # ── Allow unfree packages (VSCode, etc.) ────────────────────────────────────
  nixpkgs.config.allowUnfree = true;

  # ── System Packages ─────────────────────────────────────────────────────────
  environment.systemPackages = with pkgs; [

    ##- Core tools
    git
    curl
    wget
    unzip
    gnumake
    gcc

    ##- Shell & navigation
    zsh
    eza        # modern ls replacement
    jump       # smart directory navigation (provides `j`)
    mc         # midnight commander
    ranger     # terminal file manager

    ##- Node / JS tooling
    fnm        # fast node manager

    ##- Terminals
    wezterm
    tabby      # Note: if tabby causes issues, install via flatpak instead
               # (flatpak install flathub dev.eugeny.Tabby)

    ##- Editor
    vscode

    ##- Utilities
    nmap
    htop
    tree

  ];

  # ── Flatpak (optional fallback for apps not in nixpkgs) ─────────────────────
  services.flatpak.enable = true;
  xdg.portal.enable = true;

  # ── This value determines NixOS compatibility — do not change ───────────────
  system.stateVersion = "24.11";
}
