#!/usr/bin/env python3
"""Render a bounded Google Drive index from the Drive API.

Reads JSON on stdin: {"alias":..., "email":..., "folders":[...], "recent":[...],
"skipped":[...], "caps":{...}}. Writes markdown to stdout.

Deliberately bounded. The point of this index is orientation — "what is in Drive
and roughly where" — not a mirror. A complete listing would be large, would churn
on every sync, and would duplicate what `lifeos drive search` already answers
better.
"""

import argparse
import json
import sys
from datetime import datetime, timezone

FOLDER_MIME = "application/vnd.google-apps.folder"

TYPE_LABEL = {
    "application/vnd.google-apps.document": "Doc",
    "application/vnd.google-apps.spreadsheet": "Sheet",
    "application/vnd.google-apps.presentation": "Slides",
    "application/vnd.google-apps.form": "Form",
    "application/vnd.google-apps.drawing": "Drawing",
    "application/pdf": "PDF",
    "application/vnd.google.colaboratory": "Colab",
    "application/vnd.google-apps.script": "Script",
    "application/vnd.google-apps.shortcut": "Shortcut",
    FOLDER_MIME: "Folder",
}


def label(mime):
    if mime in TYPE_LABEL:
        return TYPE_LABEL[mime]
    if mime.startswith("image/"):
        return "Image"
    if mime.startswith("video/"):
        return "Video"
    if "wordprocessing" in mime:
        return "Word"
    if "spreadsheet" in mime:
        return "Excel"
    return mime.split("/")[-1][:12]


def days_since(stamp):
    if not stamp:
        return None
    try:
        then = datetime.fromisoformat(stamp.replace("Z", "+00:00"))
    except ValueError:
        return None
    return (datetime.now(timezone.utc) - then).days


def link(f):
    if f.get("mimeType") == FOLDER_MIME:
        return "https://drive.google.com/drive/folders/%s" % f["id"]
    return f.get("webViewLink") or "https://drive.google.com/file/d/%s/view" % f["id"]


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.parse_args()
    d = json.load(sys.stdin)
    caps = d.get("caps", {})
    out = [
        "# Google Drive Index",
        "",
        "**Generated by `lifeos drive sync`.** Do not hand-edit — it is rewritten wholesale.",
        "",
        "Last refreshed: %s" % datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        "",
        "Account: `%s` (%s)" % (d.get("alias", "?"), d.get("email", "?")),
        "",
        "**This is an orientation layer, not a mirror** (LifeOS policy 0002). It carries top-level"
        " structure and recent activity so an agent can see the shape of Drive and decide where to"
        " look. To find a specific file, use `lifeos drive search` — that is live and this is not.",
        "",
        "Bounds: %d top-level folders, %d children shown per folder, %d recently-modified files"
        " from the last %d days."
        % (
            caps.get("max_folders", 0),
            caps.get("children_per_folder", 0),
            caps.get("max_recent", 0),
            caps.get("recent_days", 0),
        ),
        "",
        "---",
        "",
    ]

    folders = d.get("folders", [])
    out += ["## Top-Level Folders", ""]
    if not folders:
        out += ["_None found._", ""]
    for f in folders:
        n = f.get("child_count")
        suffix = ""
        if n is not None:
            suffix = " — %d item%s%s" % (n, "" if n == 1 else "s", "+" if f.get("child_truncated") else "")
        out.append("### [%s](%s)%s" % (f["name"], link(f), suffix))
        out.append("")
        kids = f.get("children", [])
        if kids:
            for k in kids:
                age = days_since(k.get("modifiedTime"))
                out.append(
                    "- [%s](%s) · %s%s"
                    % (k["name"], link(k), label(k.get("mimeType", "")),
                       " · %sd" % age if age is not None else "")
                )
            if f.get("child_truncated"):
                out.append("- _…more, truncated at %d_" % caps.get("children_per_folder", 0))
        else:
            out.append("_Empty, or nothing listed._")
        out.append("")

    recent = d.get("recent", [])
    out += ["---", "", "## Recently Modified", ""]
    if recent:
        out += ["The most recently touched files across this account. Useful for spotting what is"
                " actively being worked on outside the vault.", "",
                "| Modified | Type | File |", "|---|---|---|"]
        for f in recent:
            age = days_since(f.get("modifiedTime"))
            out.append("| %s | %s | [%s](%s) |"
                       % ("%sd ago" % age if age is not None else "?", label(f.get("mimeType", "")),
                          f["name"], link(f)))
    else:
        out.append("_None found._")
    out.append("")

    skipped = d.get("skipped", [])
    if skipped:
        out += ["---", "", "## Deliberately Not Listed", "",
                "These folders are excluded by configuration. The exclusion is a privacy boundary,"
                " not an oversight — see the `lifeos-drive` skill.", ""]
        for s in skipped:
            out.append("- `%s`" % s)
        out.append("")

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
